<?php

/**
 * @file
 * Open Y Memberships module file.
 */

/**
 * Implements hook_menu_links_discovered_alter().
 */
function openy_memberships_menu_links_discovered_alter(&$links) {
  // Move the Commerce links to the Memberships menu.
  $links['commerce.admin_commerce']['parent'] = 'openy_memberships.openy_memberships';
}

/**
 * Implements hook_page_attachments().
 */
function openy_memberships_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'openy_memberships/library';
}

/**
 * Implements hook_theme().
 */
function openy_memberships_theme() {
  return [
    'openy_memberships__pdf__summary' => [
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}


/**
 * @param $key
 * @param $message
 * @param $params
 * Implements hook_mail()
 */
function openy_memberships_mail($key, &$message, $params) {

  switch ($key) {
    case 'openy_memberships_summary_email':
      $headers = [
        'MIME-Version'              => '1.0',
        'Content-Type'              => 'text/html; charset=UTF-8; format=flowed; delsp=yes',
        'Content-Transfer-Encoding' => '8Bit',
        'X-Mailer'                  => 'Drupal',
      ];
      foreach ($headers as $key => $value) {
        $message['headers'][$key] = $value;
      }
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }

}
